{
 "title": "SSH Honeypot",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"ssh-honeypot\",\n  tag: \"country\",\n  predicate: (r) => true,\n  start: v.timeRangeStart\n)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Map of requests",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ssh-honeypot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\n  |> filter(fn: (r) => r[\"country\"] =~ /${country:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()"
    }
   ]
  },
  {
   "title": "Requests by Country",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"ssh-honeypot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\")\n  |> filter(fn: (r) => r[\"country\"] =~ /${country:regex}/)\n  |> group(columns: [\"country\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Heat map by country",
   "type": "heatmap",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"ssh-honeypot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\")\n  |> filter(fn: (r) => r[\"country\"] =~ /${country:regex}/)\n  |> group(columns: [\"country\"])\n  |> aggregateWindow(every: 1h, fn: count, createEmpty: true)"
    }
   ]
  },
  {
   "title": "List of attempts",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "query": "from(bucket: \"ssh-honeypot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\n  |> filter(fn: (r) => r[\"country\"] =~ /${country:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"local_port\", \"local_host\", \"longitude\", \"latitude\", \"ip\"])\n  |> group()"
    }
   ]
  }
 ]
}